In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\engineered_data\engineered_data.csv")

In [3]:
df

,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
0,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900,0.472609,0.046059,132,long,expensive
1,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970,0.592308,0.039427,84,long,affordable
2,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728,0.408654,0.041363,161,long,affordable
3,360,171,1726,7.9,401,61.7,107,500,363,103,39.990,0.576636,0.035747,41,middle,cheap
4,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970,0.545455,0.032485,78,long,cheap
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,325,209,1955,9.6,296,68.0,50,0,467,131,42.575,1.360000,0.034783,-29,short,cheap
1196,265,260,2131,13.1,252,69.0,77,1000,550,227,60.155,0.896104,0.032379,-13,short,affordable
1197,265,260,2161,13.1,252,69.0,77,1000,980,263,69.695,0.896104,0.031930,-13,short,expensive
1198,185,250,1969,12.1,196,46.3,74,1000,550,318,58.830,0.625676,0.023514,11,short,affordable
1199,180,257,1989,12.1,189,46.3,74,1000,980,381,68.580,0.625676,0.023278,9,short,expensive

In [6]:
cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

In [9]:
mapping = {'Price_level2' : ['cheap','affordable','expensive']}
mapping1 = {'Range_level2' : ['short','middle','long']}

In [18]:
encoder = OrdinalEncoder(categories=[['cheap','affordable','expensive']], 
                         handle_unknown='use_encoded_value', 
                         unknown_value=-1,
                         dtype=int
                         )

df[['Price_level']] =encoder.fit_transform(df[['Price_level']])

In [21]:
encoder = OrdinalEncoder(categories=[['short','middle','long']], 
                         handle_unknown='use_encoded_value', 
                         unknown_value=-1,
                         dtype=int
                         )

df[['Range_km_level']] =encoder.fit_transform(df[['Range_km_level']])

In [22]:
df

,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
0,610,178,2360,4.9,742,108.7,230,2000,578,114,70.900,0.472609,0.046059,132,2,2
1,490,157,1953,7.2,574,77.0,130,1600,952,100,47.970,0.592308,0.039427,84,2,1
2,585,145,2055,6.7,746,85.0,208,1500,506,92,55.728,0.408654,0.041363,161,2,1
3,360,171,1726,7.9,401,61.7,107,500,363,103,39.990,0.576636,0.035747,41,1,0
4,445,135,1847,6.2,523,60.0,110,1000,682,89,37.970,0.545455,0.032485,78,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,325,209,1955,9.6,296,68.0,50,0,467,131,42.575,1.360000,0.034783,-29,0,0
1196,265,260,2131,13.1,252,69.0,77,1000,550,227,60.155,0.896104,0.032379,-13,0,1
1197,265,260,2161,13.1,252,69.0,77,1000,980,263,69.695,0.896104,0.031930,-13,0,2
1198,185,250,1969,12.1,196,46.3,74,1000,550,318,58.830,0.625676,0.023514,11,0,1
1199,180,257,1989,12.1,189,46.3,74,1000,980,381,68.580,0.625676,0.023278,9,0,2

In [28]:
df.corrwith(df['Price_level']).sort_values(ascending=False)

Price_level            1.000000
Weight_kg              0.817119
Battery_kWh            0.772543
Price_Euro             0.739348
Range_km               0.609682
Fast_charger(kW)       0.602382
Firth_stop_range_km    0.593894
Range_km_level         0.587288
Energy_weight_ratio    0.546860
Price/Range(km)        0.499963
Efficiency             0.407342
Towing_kg              0.402578
Added_Range_1Stop      0.378775
Cargo_volume           0.259455
FastCharge_time_hrs   -0.117509
Acceleration(0-100)   -0.576027
dtype: float64

In [41]:
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

In [42]:
to_remove = ['Range_km','Efficiency']

to_remove in num_cols

False

In [ ]:
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
to_remove = ['Range_km','Efficiency']

if to_remove in num_cols:
    num_cols = [col for col in num_cols if col not in to_remove]
num_cols

In [ ]:
num_cols

In [3]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\preprocessed_data\preprocessed_data.csv")

In [4]:
df

,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
0,0.826772,0.370968,0.650771,0.142157,0.878080,0.868203,0.696970,0.666667,0.2890,0.042895,0.149124,0.258458,0.935048,0.826613,1.0,1.0
1,0.637795,0.258065,0.454721,0.254902,0.660182,0.576037,0.393939,0.533333,0.4760,0.024129,0.085801,0.323918,0.755589,0.633065,1.0,0.5
2,0.787402,0.193548,0.503854,0.230392,0.883268,0.649770,0.630303,0.500000,0.2530,0.013405,0.107226,0.223483,0.807970,0.943548,1.0,0.5
3,0.433071,0.333333,0.345376,0.289216,0.435798,0.435023,0.324242,0.166667,0.1815,0.028150,0.063764,0.315348,0.656045,0.459677,0.5,0.0
4,0.566929,0.139785,0.403661,0.205882,0.594034,0.419355,0.333333,0.333333,0.3410,0.009383,0.058186,0.298295,0.567780,0.608871,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,0.377953,0.537634,0.455684,0.372549,0.299611,0.493088,0.151515,0.000000,0.2335,0.065684,0.070903,0.743750,0.629941,0.177419,0.0,0.0
1196,0.283465,0.811828,0.540462,0.544118,0.242542,0.502304,0.233333,0.333333,0.2750,0.194370,0.119451,0.490057,0.564913,0.241935,0.0,0.5
1197,0.283465,0.811828,0.554913,0.544118,0.242542,0.502304,0.233333,0.333333,0.4900,0.242627,0.145796,0.490057,0.552751,0.241935,0.0,1.0
1198,0.157480,0.758065,0.462428,0.495098,0.169909,0.293088,0.224242,0.333333,0.2750,0.316354,0.115792,0.342166,0.325067,0.338710,0.0,0.5
1199,0.149606,0.795699,0.472062,0.495098,0.160830,0.293088,0.224242,0.333333,0.4900,0.400804,0.142717,0.342166,0.318670,0.330645,0.0,1.0