In [4]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [ ]:
from sklearn.ensemble import (
    BaggingClassifier,
    GradientBoostingClassifier,
    VotingClassifier,
    StackingClassifier
)

ImportError: cannot import name 'XGBClassifier' from 'sklearn.ensemble' (c:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\myEnv\Lib\site-packages\sklearn\ensemble\__init__.py)

In [ ]:
#bagging
bagging = BaggingClassifier(
    n_estimators= 100,
    estimator=DecisionTreeClassifier(),
    random_state=99
)


#boosting
boosting = GradientBoostingClassifier(
    learning_rate=0.05,
    n_estimators=99,
    max_depth=5
)


#voting
voting = [
    ('lr',LogisticRegression(max_iter=999)),
    ('rf',DecisionTreeClassifier(random_state=34,max_depth=6)),
    ('gr',GradientBoostingClassifier(n_estimators=46))
]
voting_model = VotingClassifier(estimators=voting)


#stacking
stacking = [
    ('l2',Lasso()),
    ('lr',LogisticRegression(max_iter=999)),
    ('dt',DecisionTreeClassifier(max_depth=5,random_state=55))
]
stacking_model = StackingClassifier(
    estimators=stacking,
    final_estimator=RandomForestClassifier(max_depth=5,random_state=99)
)

models = {
    'bagging':bagging,
    'boosting':boosting,
    'voting': voting_model,
    'stacking': stacking_model
}

for name,model in models.items():
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    
    accuracy = accuracy_score(y_test,y_pred)
    print(f"{name:10} | accuracy Score: {accuracy:.3f} |")

In [16]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\sampled_data\sampled_data.csv")

In [9]:
df.sample(2)

     Efficiency  Weight_kg  ...  Range_km_level  Price_level
353    0.440860   0.682081  ...               1            2
612    0.435484   0.552505  ...               1            2

[2 rows x 14 columns]

In [10]:
x = df.drop(columns=['Range_km_level','Price_level'])
y = df[['Range_km_level','Price_level']]

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.19,random_state=99)

In [ ]:
from sklearn.ensemble import (
    BaggingClassifier,
    GradientBoostingClassifier,
    VotingClassifier,
    StackingClassifier,
    RandomForestClassifier,
    ExtraTreesClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

# BAGGING
bagging_base = BaggingClassifier(
    estimator=DecisionTreeClassifier(random_state=42),
    n_estimators=100,
    random_state=99
)
bagging_model = MultiOutputClassifier(bagging_base)


# BOOSTING (XGBoost)
boosting_base = XGBClassifier(
    learning_rate=0.05, 
    n_estimators=99, 
    max_depth=5, 
    random_state=42
)
boosting_model = MultiOutputClassifier(boosting_base)


# VOTING
voting_base = VotingClassifier(
    estimators=[
        ('rf', RandomForestClassifier(random_state=42)),
        ('knn', KNeighborsClassifier()),
        ('lr', LogisticRegression(max_iter=1000))
    ],
    voting='hard'
)
voting_model = MultiOutputClassifier(voting_base)


#  STACKING
stacking_base = StackingClassifier(
    estimators=[
        ('xt', ExtraTreesClassifier(random_state=42)),
        ('lr', LogisticRegression(max_iter=1000)),
        ('svm', SVC(random_state=42))
    ],
    final_estimator=RandomForestClassifier(max_depth=5, random_state=99)
)
stacking_model = MultiOutputClassifier(stacking_base)


models = {
    'Bagging': bagging_model,
    'Boosting (XGB)': boosting_model,
    'Voting': voting_model,
    'Stacking': stacking_model
}


for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f"\n{'-'*30}\n{name} natijasi")
    
    
    y_test_np = np.array(y_test)
    
    for i in range(y_test_np.shape[1]):
        y_test_col = y_test_np[:, i]
        y_pred_col = y_pred[:, i]
        
        accuracy = accuracy_score(y_test_col, y_pred_col)
        print(f"  Target {i+1} (Ustun {i+1}) Accuracy: {accuracy:.3f}")

------------------------------
Bagging natijalari:
  Target 1 (Ustun 1) Accuracy: 0.936
  Target 2 (Ustun 2) Accuracy: 0.859

------------------------------
Boosting (XGB) natijalari:
  Target 1 (Ustun 1) Accuracy: 0.927
  Target 2 (Ustun 2) Accuracy: 0.873

------------------------------
Voting natijalari:
  Target 1 (Ustun 1) Accuracy: 0.911
  Target 2 (Ustun 2) Accuracy: 0.848

------------------------------
Stacking natijalari:
  Target 1 (Ustun 1) Accuracy: 0.925
  Target 2 (Ustun 2) Accuracy: 0.876

In [28]:
np.array(y_test)[:,1]

array([2, 1, 1, ..., 2, 2, 2], shape=(1062,))

In [20]:
y_test

      Range_km_level  Price_level
680                2            2
363                2            1
153                1            1
504                1            0
86                 1            1
...              ...          ...
303                0            0
1123               2            2
1220               2            2
940                2            2
67                 1            2

[1062 rows x 2 columns]