In [12]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [13]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\preprocessed_data\preprocessed_data.csv")

In [14]:
df.sample(2)

,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
477,0.700787,0.612903,0.884393,0.132353,0.619974,0.953917,0.484848,0.600000,0.3225,0.296247,0.361827,0.40332,0.811047,0.346774,1.0,1.0
806,0.314961,0.392473,0.460501,0.343137,0.306096,0.345622,0.212121,0.333333,0.2715,0.096515,0.063668,0.40625,0.404846,0.358871,0.0,0.0

In [15]:
df['Range_km_level'].value_counts()

Range_km_level
0.5    413
0.0    402
1.0    385
Name: count, dtype: int64

In [16]:
df['Price_level'].value_counts()

Price_level
0.5    435
1.0    397
0.0    368
Name: count, dtype: int64

In [17]:
df['Range_km_level'] = df['Range_km_level'].replace([0.0,0.5,1.0],[0,1,2]).astype(int)
df['Price_level'] = df['Price_level'].replace([0.0,0.5,1.0], [0,1,2]).astype(int)
df = df.drop(columns=['Range_km','Price_Euro'])

In [18]:
df.head()

,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
0,0.370968,0.650771,0.142157,0.878080,0.868203,0.696970,0.666667,0.2890,0.042895,0.258458,0.935048,0.826613,2,2
1,0.258065,0.454721,0.254902,0.660182,0.576037,0.393939,0.533333,0.4760,0.024129,0.323918,0.755589,0.633065,2,1
2,0.193548,0.503854,0.230392,0.883268,0.649770,0.630303,0.500000,0.2530,0.013405,0.223483,0.807970,0.943548,2,1
3,0.333333,0.345376,0.289216,0.435798,0.435023,0.324242,0.166667,0.1815,0.028150,0.315348,0.656045,0.459677,1,0
4,0.139785,0.403661,0.205882,0.594034,0.419355,0.333333,0.333333,0.3410,0.009383,0.298295,0.567780,0.608871,2,0

# Smote

In [19]:
x = df.drop(columns=['Price_level'])
y = df['Price_level']
smote = SMOTE(random_state=99)


x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.19, random_state=99)

print(f"Before sampling\n : {y_train.value_counts()}")

x_train_balanced, y_train_balanced = smote.fit_resample(x_train,y_train)
print(f"\nAfter sampling:\n {y_train_balanced.value_counts()}")

Before sampling
 : Price_level
1    361
2    307
0    304
Name: count, dtype: int64

After sampling:
 Price_level
1    361
2    361
0    361
Name: count, dtype: int64

In [20]:
df_train = x_train_balanced.copy()
df_train['Price_level'] = y_train_balanced

df_test = x_test.copy()
df_test['Price_level'] = y_test

df_final_price = pd.concat([df_train,df_test], axis=0, ignore_index=True)
df_final_price.info()

<class 'pandas.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Efficiency           1311 non-null   float64
 1   Weight_kg            1311 non-null   float64
 2   Acceleration(0-100)  1311 non-null   float64
 3   Firth_stop_range_km  1311 non-null   float64
 4   Battery_kWh          1311 non-null   float64
 5   Fast_charger(kW)     1311 non-null   float64
 6   Towing_kg            1311 non-null   float64
 7   Cargo_volume         1311 non-null   float64
 8   Price/Range(km)      1311 non-null   float64
 9   FastCharge_time_hrs  1311 non-null   float64
 10  Energy_weight_ratio  1311 non-null   float64
 11  Added_Range_1Stop    1311 non-null   float64
 12  Range_km_level       1311 non-null   int64
 13  Price_level          1311 non-null   int64
dtypes: float64(12), int64(2)
memory usage: 143.5 KB

# datani saqlash

In [21]:
import os
path = r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\sampled_data"
full_path = os.path.join(path, 'sampled_data.csv')
df_final_price.to_csv(full_path, index=False)

In [22]:
# y_range = df['Range_km_level']
# x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(x, y_range, test_size=0.19, random_state=99)
# smote_r = SMOTE(random_state=99)
# x_train_range_bal, y_train_range_bal = smote_r.fit_resample(x_train_r, y_train_r)

# print(f"{y_train_range_bal.value_counts()}")

In [23]:
# df_train = x_train_range_bal.copy()
# df_train['Range_km_level'] = y_train_range_bal

# df_test = x_test_r.copy()
# df_test['Range_km_level'] = y_test_r

# df_final_range = pd.concat([df_train, df_test], axis=0, ignore_index=True)
# df_final_range.info()