In [104]:
import pandas as pd
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

In [105]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\preprocessed_data\preprocessed_data.csv")

In [106]:
df.sample(2)

,Range_km,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
634,0.110236,0.349462,0.267823,0.450980,0.125811,0.115207,0.121212,0.00,0.1405,0.156836,0.033111,0.369141,0.155639,0.322581,0.0,0.0
820,0.582677,0.704301,0.826590,0.044118,0.632944,0.870968,0.745455,0.75,0.3285,0.328418,0.356489,0.242315,0.771105,0.689516,1.0,1.0

In [107]:
df['Range_km_level'].value_counts()

Range_km_level
0.5    413
0.0    402
1.0    385
Name: count, dtype: int64

In [108]:
df['Price_level'].value_counts()

Price_level
0.5    435
1.0    397
0.0    368
Name: count, dtype: int64

In [109]:
df['Range_km_level'] = df['Range_km_level'].replace([0.0,0.5,1.0],[1,2,3]).astype(int)
df['Price_level'] = df['Price_level'].replace([0.0,0.5,1.0], [1,2,3]).astype(int)
df = df.drop('Range_km',axis=1)

In [110]:
df

,Efficiency,Weight_kg,Acceleration(0-100),Firth_stop_range_km,Battery_kWh,Fast_charger(kW),Towing_kg,Cargo_volume,Price/Range(km),Price_Euro,FastCharge_time_hrs,Energy_weight_ratio,Added_Range_1Stop,Range_km_level,Price_level
0,0.370968,0.650771,0.142157,0.878080,0.868203,0.696970,0.666667,0.2890,0.042895,0.149124,0.258458,0.935048,0.826613,3,3
1,0.258065,0.454721,0.254902,0.660182,0.576037,0.393939,0.533333,0.4760,0.024129,0.085801,0.323918,0.755589,0.633065,3,2
2,0.193548,0.503854,0.230392,0.883268,0.649770,0.630303,0.500000,0.2530,0.013405,0.107226,0.223483,0.807970,0.943548,3,2
3,0.333333,0.345376,0.289216,0.435798,0.435023,0.324242,0.166667,0.1815,0.028150,0.063764,0.315348,0.656045,0.459677,2,1
4,0.139785,0.403661,0.205882,0.594034,0.419355,0.333333,0.333333,0.3410,0.009383,0.058186,0.298295,0.567780,0.608871,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,0.537634,0.455684,0.372549,0.299611,0.493088,0.151515,0.000000,0.2335,0.065684,0.070903,0.743750,0.629941,0.177419,1,1
1196,0.811828,0.540462,0.544118,0.242542,0.502304,0.233333,0.333333,0.2750,0.194370,0.119451,0.490057,0.564913,0.241935,1,2
1197,0.811828,0.554913,0.544118,0.242542,0.502304,0.233333,0.333333,0.4900,0.242627,0.145796,0.490057,0.552751,0.241935,1,3
1198,0.758065,0.462428,0.495098,0.169909,0.293088,0.224242,0.333333,0.2750,0.316354,0.115792,0.342166,0.325067,0.338710,1,2
1199,0.795699,0.472062,0.495098,0.160830,0.293088,0.224242,0.333333,0.4900,0.400804,0.142717,0.342166,0.318670,0.330645,1,3

# Smote

In [111]:
x = df.drop(columns=['Price_level'])
y = df['Price_level']
smote = SMOTE(random_state=99)


x_train, x_test, y_train,y_test = train_test_split(x, y, test_size=0.19, random_state=99)

print(f"Before sampling\n : {y_train.value_counts()}")

x_train_balanced, y_train_balanced = smote.fit_resample(x_train,y_train)
print(f"\nAfter sampling:\n {y_train_balanced.value_counts()}")

Before sampling
 : Price_level
2    361
3    307
1    304
Name: count, dtype: int64

After sampling:
 Price_level
2    361
3    361
1    361
Name: count, dtype: int64

In [112]:
df_train = x_train_balanced.copy()
df_train['Price_level'] = y_train_balanced

df_test = x_test.copy()
df_test['Price_level'] = y_test

df_final_price = pd.concat([df_train,df_test], axis=0, ignore_index=True)
df_final_price.info()

<class 'pandas.DataFrame'>
RangeIndex: 1311 entries, 0 to 1310
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Efficiency           1311 non-null   float64
 1   Weight_kg            1311 non-null   float64
 2   Acceleration(0-100)  1311 non-null   float64
 3   Firth_stop_range_km  1311 non-null   float64
 4   Battery_kWh          1311 non-null   float64
 5   Fast_charger(kW)     1311 non-null   float64
 6   Towing_kg            1311 non-null   float64
 7   Cargo_volume         1311 non-null   float64
 8   Price/Range(km)      1311 non-null   float64
 9   Price_Euro           1311 non-null   float64
 10  FastCharge_time_hrs  1311 non-null   float64
 11  Energy_weight_ratio  1311 non-null   float64
 12  Added_Range_1Stop    1311 non-null   float64
 13  Range_km_level       1311 non-null   int64
 14  Price_level          1311 non-null   int64
dtypes: float64(13), int64(2)
memory usage: 153.8 KB

# datani saqlash

In [116]:
import os
path = r"C:\Users\bunyo\OneDrive\Desktop\AI_Course\ModularProgramProjects\finalProject\data\sampled_data"
full_path = os.path.join(path, 'sampled_data.csv')
df_final_price.to_csv(full_path, index=False)

In [113]:
# y_range = df['Range_km_level']
# x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(x, y_range, test_size=0.19, random_state=99)
# smote_r = SMOTE(random_state=99)
# x_train_range_bal, y_train_range_bal = smote_r.fit_resample(x_train_r, y_train_r)

# print(f"{y_train_range_bal.value_counts()}")

In [114]:
# df_train = x_train_range_bal.copy()
# df_train['Range_km_level'] = y_train_range_bal

# df_test = x_test_r.copy()
# df_test['Range_km_level'] = y_test_r

# df_final_range = pd.concat([df_train, df_test], axis=0, ignore_index=True)
# df_final_range.info()